language: python
python:
  - "3.6"
sudo: false
cache: pip
addons:
  apt:
    packages:
    - wget
    - libgmp-dev
    - libffi6
before_install:
- export PATH=$HOME/.local/bin:$PATH
- wget https://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
- tar xf futhark-nightly-linux-x86_64.tar.xz
- "(cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)"
install: pip install --user -q -r requirements.txt
script:
- make html
- make -C src test
