language: c

sudo: true

matrix:
  include:
    - env: BUILD=stack STACK_YAML=stack.yaml

addons:
  apt:
    packages:
    - wget
    - libgmp-dev
    - libffi6
    - libc6:i386

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

before_install:
 - sudo apt-get update
 - sudo apt-get install texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng
 # install Haskell stack
 - export PATH=$HOME/.local/bin:$PATH
 - ./.travis-setup.sh
 # install Futhark
 - wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
 - tar xf futhark-nightly-linux-x86_64.tar.xz
 - (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)

install:
 # make the book
 - make

script:
 # execute tests
 - make test

deploy:
  provider: releases
  api_key:
    secure:
  file: main.pdf
  skip_cleanup: true
  on:
    tags: true
    repo: hiperfit/futhark-book
