dist: trusty
sudo: false
matrix:
  include:
  - env: BUILD=stack STACK_YAML=stack.yaml
addons:
  apt:
    packages:
    - wget
    - libgmp-dev
    - libffi6
    - libc6:i386
    - texlive-full
cache:
  apt: 
  directories:
  - "$HOME/.ghc"
  - "$HOME/.cabal"
  - "$HOME/.stack"
before_install:
- export PATH=$HOME/.local/bin:$PATH
- wget https://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
- tar xf futhark-nightly-linux-x86_64.tar.xz
- "(cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)"
install:
- make
script:
- make test
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: dpqGWpaaeea2JHUhiLaE1vswZZe+qKZqsmSYXUhcX8Y7amsgVaX4K6pCZJiZ2u0XFZ19re3YjPLP625djRPu7L1WQ8evdns2yhfsNNWxNphiYQKEN2t7igOmYPmyAHKCkV9dTPZKdghtp7mwL6meHB4BzgUg2ONrh44B++vkvLc19GTkWCDLwdphWzQOOLQ0l9+YihOkYz5k4RrkC+r34YP8w6yVudpKDLLwOOf9juZLNLSR8MlsXCrOc3HjU/kHX+hHZEYlbo9ebxN5AGtkmnDbb1dZ24vUuWeg8kPmUgM1ZNJLDRec7ALOTRhW9OexR9goOowDREQz/bwSzkFSfBfQYMEuN4XKj9dTe9b/699vo+8bNLP+mNGpci2dbE+Lc2h4wXERhtJvTNa54IzDAbCGRAsEu/HYx4gKLdde1y9oGqutpEvy9SAwN3fGkyiaKKz3KFFsKxy/VsNuzX0fyGKIWCXhsjtnKbZNpDAYnYMkpin5hyCCtyRIN3HGNK+ry+zo1HDJEClcJ3IXPzkcceexPhJ+TUQK8rjoUvZW9CfZ2sRrbGn+fpJkUDJMRcIEwXVfr7oY/wSibnxTr+u2T4XoDKY0yVZ8s4LA9KEXI/plr1fUMvmHLQT4bRLv6bwkPnFj5V1WNqTCfNacBf41kCronp+qW/3ehljQ/MABHB4=
  file: main.pdf
  on:
    repo: diku-dk/futhark-book
