dist: trusty
sudo: false

matrix:
  include:
    - env: BUILD=stack STACK_YAML=stack.yaml

addons:
  apt:
    packages:
    - wget
    - libgmp-dev
    - libffi6
    - libc6:i386
    - texlive-full

cache:
  apt:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

before_install:
 # install Haskell stack
 - export PATH=$HOME/.local/bin:$PATH
 # install Futhark
 - wget https://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
 - tar xf futhark-nightly-linux-x86_64.tar.xz
 - (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)

install:
 # make the book
 - make

script:
 # execute tests
 - make test

deploy:
  provider: releases
  api_key:
    secure:
  file: main.pdf
  skip_cleanup: true
  on:
    tags: true
    repo: diku-dk/futhark-book
